
curl https://translate.google.co.kr/?hl=ko

//https://www.nasdaq.com/market-activity/stocks/screener
// 전체주식목록
###


GET https://api.nasdaq.com/api/screener/stocks?&download=true&exchange=NASDAQ
cache-control: max-age=0
accept: application/json
###
GET https://api.nasdaq.com/api/screener/stocks?&download=true&exchange=NYSE
cache-control: max-age=0
accept: application/json
###
GET https://api.nasdaq.com/api/screener/stocks?&download=true&exchange=AMEX
cache-control: max-age=0
accept: application/json
###
